# Generated by Django 4.0 on 2022-01-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparkmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='autoparkmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
