# Generated by Django 4.0 on 2022-01-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagonal', models.IntegerField()),
                ('CPU', models.CharField(max_length=255)),
                ('RAM', models.IntegerField()),
                ('camera', models.IntegerField()),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
                ('model', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phones',
            },
        ),
    ]
