# Generated by Django 4.0 on 2022-01-11 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_remove_phonemodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='CPU',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='RAM',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='camera',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(128)]),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='diagonal',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2700), django.core.validators.MaxValueValidator(28000)]),
        ),
    ]
