# Generated by Django 4.0 on 2022-01-11 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_alter_phonemodel_cpu_alter_phonemodel_ram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='CPU',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='RAM',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='camera',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(128)]),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='diagonal',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
