# Generated by Django 4.0 on 2022-01-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RAM', models.IntegerField()),
                ('processor', models.CharField(max_length=255)),
                ('diagonal', models.IntegerField()),
            ],
            options={
                'db_table': 'computers',
            },
        ),
    ]
