# Generated by Django 4.0 on 2022-01-13 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPU', models.CharField(max_length=255)),
                ('memory', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)])),
                ('storage', models.IntegerField(validators=[django.core.validators.MinValueValidator(256), django.core.validators.MaxValueValidator(1024)])),
                ('motherboard', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'computers',
            },
        ),
    ]
