# Generated by Django 4.0 on 2022-01-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoparks', '0002_alter_autoparkmodel_created_and_more'),
        ('cars', '0002_alter_carmodel_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='autopark',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='autoparks.autoparkmodel'),
            preserve_default=False,
        ),
    ]
